spring.datasource.url=jdbc:mariadb://${DB_HOST:localhost}:3306/agenda_test
spring.datasource.username=agenda_user_test
spring.datasource.password=1234
spring.jpa.hibernate.ddl-auto=create
services.publicacion.url=http://${PUBLICACION_URL:localhost}:8085/api/v1/publicacion
