spring.application.name=agenda
spring.output.ansi.enabled=always
spring.data.web.pageable.serialization-mode=via-dto
spring.jackson.serialization.fail-on-empty-beans=false
spring.jpa.show-sql=true
spring.jpa.open-in-view=false
server.port=${SERVER_PORT:8082}
